# Generated by Django 6.0.1 on 2026-01-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_id_product__id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='_id',
        ),
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
