# Generated by Django 6.0.1 on 2026-01-11 17:16

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_id_product__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='_id',
            field=models.IntegerField(default=products.models.generate_product_id, editable=False, primary_key=True, serialize=False),
        ),
    ]
